### ISSUE TITLE
Errant line when tracing along antialiased edge

### ISSUE THREAD

**Issue by pklauzinski** [tooolbox/node-potrace#11]
I've encountered an odd issue when tracing a seemingly normal image. An errant line appears along the right side of the "S" where the image ends.

This is the original image:
![original image](https://customops-sandbox.s3.amazonaws.com/auto/051a5ab9-42f2-48ab-a7a8-8ca850cf55ef/rambler-tumbler-20oz-navy/front/autoimage/1597334852165/upload.png)

This is the SVG created from the trace:
![traced SVG](https://customops-sandbox.s3.amazonaws.com/auto/051a5ab9-42f2-48ab-a7a8-8ca850cf55ef/rambler-tumbler-20oz-navy/front/autoimage/1597334796629/art.svg)

Any ideas on why this is happening? I'm thinking it has something to do with the antialiased edge of the "S" butting up against the edge of the image, but I would think that is a pretty typical use-case, and I've only seen it happen with this one particular image so far.

I am able correct for this by first adding a pixel of whitespace around the edges of the image, and then the trace works as expected, but I would prefer to not have to do that if it can be avoided.

**Comment by tooolbox** [comment]
> Any ideas on why this is happening? I'm thinking it has something to do with the antialiased edge of the "S" butting up against the edge of the image

Pretty sure you hit the nail on the head, there.

> I am able correct for this by first adding a pixel of whitespace around the edges of the image

Glad there's a workaround!

I am curious if the non-Node version does the same thing: http://kilobtye.github.io/potrace/

Regardless, this is not something I have time to dive into with my current schedule.  A PR that fixes this without negatively impacting the majority of use cases would be appreciated, if you're able.

Alternatively, if you expect to continue to encounter this and are okay with the overhead, perhaps you can use JIMP or an equivalent to expand the image by one pixel before tracing and then trim it back off when done, as part of whatever automated workflow you have.

**Comment by pklauzinski** [comment]
> I am curious if the non-Node version does the same thing: http://kilobtye.github.io/potrace/

Nope, the non-Node version does not add the errant line.
 
> Regardless, this is not something I have time to dive into with my current schedule. A PR that fixes this without negatively impacting the majority of use cases would be appreciated, if you're able.
> 
> Alternatively, if you expect to continue to encounter this and are okay with the overhead, perhaps you can use JIMP or an equivalent to expand the image by one pixel before tracing and then trim it back off when done, as part of whatever automated workflow you have.

I actually went ahead with a fix to add the pixel of whitespace and then I trim it back later in the workflow because this is a production application, but I was just curious about any input because I thought it was an unusual case. I trim all whitespace from every image before tracing it, and this is the only image I have seen this happen on, though we are tracing thousands, so there could be more.

Thanks for the quick reply!

**Comment by tooolbox** [comment]
> Nope, the non-Node version does not add the errant line.

Interesting, alright.

I feel like the differences were introduced somewhere in here:

- https://github.com/tooolbox/node-potrace/commit/5302dce5f2114041ba15c051f901fa878da5f6e7
- https://github.com/tooolbox/node-potrace/commit/7d94796d2996ee31e9ae85f268a2a7f4c8106b59
- https://github.com/tooolbox/node-potrace/commit/983bfc7abd0d40cd457cdde5022655d7fb30b3ad
- https://github.com/tooolbox/node-potrace/commit/645eb882a32a916067910ec22c1fecec5f30f0b8
- etc.

Unfortunately I'm not intimately familiar with the work that @Iwasawafag did.  He might have a better idea of what setting could fix that line but generally seems hard to contact.

Final thought is that you could try simply playing with the settings.  For example, what happens if you specify `128` as the `threshold` setting, to match the hardcoded value of the web version?

**Comment by pklauzinski** [comment]
> I feel like the differences were introduced somewhere in here:
> 
> * [5302dce](https://github.com/tooolbox/node-potrace/commit/5302dce5f2114041ba15c051f901fa878da5f6e7)
> * [7d94796](https://github.com/tooolbox/node-potrace/commit/7d94796d2996ee31e9ae85f268a2a7f4c8106b59)
> * [983bfc7](https://github.com/tooolbox/node-potrace/commit/983bfc7abd0d40cd457cdde5022655d7fb30b3ad)
> * [645eb88](https://github.com/tooolbox/node-potrace/commit/645eb882a32a916067910ec22c1fecec5f30f0b8)
> * etc.

Thank you for the context.

> Final thought is that you could try simply playing with the settings. For example, what happens if you specify `128` as the `threshold` setting, to match the hardcoded value of the web version?

I just tried it with the `threshold` hardcoded to `128` and it makes no difference.

**Comment by tooolbox** [comment]
> I just tried it with the threshold hardcoded to 128 and it makes no difference.

Alright, well it was worth a shot.

Given that you have a workaround I'm going to close this, but if you are able to contribute an improvement in this area feel free to reopen and/or send a PR.  Cheers!
